"""业务层依赖的存储边界。

SQLite Store 是开发实现；生产环境可以用 PostgreSQL Repository 替换，
API 层不应直接依赖具体数据库连接或 SQL 方言。
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol
from uuid import UUID

from .contracts import (
    Agent,
    AgentConnection,
    AgentRegister,
    Artifact,
    ArtifactCreate,
    Evidence,
    EvidenceCreate,
    Event,
    EventOutbox,
    GatewayCommandResult,
    Device,
    DeviceCredential,
    DevicePairing,
    DevicePairingCreate,
    DeviceProjectCredential,
    DeviceProjectGrant,
    DeviceProjectGrantCreate,
    DeviceRegisterRequest,
    DeviceRuntimeState,
    DocumentDraft,
    Gate,
    GitFileIndex,
    GitRepository,
    GitRepositoryCreate,
    Handoff,
    HandoffCreate,
    Project,
    ProjectCreate,
    Review,
    ReviewCreate,
    RiskDecisionRequest,
    RiskRegistryEntry,
    Run,
    RunComplete,
    RunCreate,
    Task,
    TaskClaimRequest,
    TaskLease,
    TaskProgressRequest,
    TaskResult,
    TaskResultSubmit,
    TaskCreate,
    TaskStatus,
)


class PlatformRepository(Protocol):
    def list_projects(self) -> list[Project]: ...
    def get_project(self, project_id: UUID) -> Project: ...
    def create_project(self, data: ProjectCreate) -> Project: ...
    def list_tasks(self, project_id: UUID) -> list[Task]: ...
    def get_task(self, task_id: UUID) -> Task: ...
    def create_task(self, project_id: UUID, data: TaskCreate) -> Task: ...
    def update_task(self, task_id: UUID, status: TaskStatus | None, assignee: str | None, blocked_reason: str | None) -> Task: ...
    def claim_task(self, task_id: UUID, data: TaskClaimRequest) -> tuple[Task, TaskLease]: ...
    def claim_next_task(self, data: TaskClaimRequest, project_id: UUID | None = None, stages: list[str] | None = None) -> tuple[Task, TaskLease] | None: ...
    def heartbeat_lease(self, lease_token: str, agent_id: str, extend_seconds: int, project_id: UUID | None = None) -> TaskLease: ...
    def update_task_progress(self, task_id: UUID, data: TaskProgressRequest) -> Task: ...
    def submit_task_result(self, task_id: UUID, data: TaskResultSubmit) -> TaskResult: ...
    def list_runs(self, project_id: UUID) -> list[Run]: ...
    def get_run(self, run_id: UUID) -> Run: ...
    def create_run(self, project_id: UUID, data: RunCreate) -> Run: ...
    def complete_run(self, run_id: UUID, data: RunComplete) -> Run: ...
    def list_handoffs(self, project_id: UUID) -> list[Handoff]: ...
    def get_handoff(self, handoff_id: UUID) -> Handoff: ...
    def create_handoff(self, project_id: UUID, data: HandoffCreate, sender_agent_id: str = "agent-platform") -> Handoff: ...
    def accept_handoff(self, handoff_id: UUID, receiver: str, actor_kind: str = "agent") -> Handoff: ...
    def reject_handoff(self, handoff_id: UUID, actor: str, reason: str, findings: list[dict[str, Any]] | None = None, actor_kind: str = "agent") -> Handoff: ...
    def list_artifacts(self, project_id: UUID) -> list[Artifact]: ...
    def get_artifact(self, artifact_id: UUID) -> Artifact: ...
    def create_artifact(self, project_id: UUID, data: ArtifactCreate, created_by: str = "member-001", created_by_kind: str = "member") -> Artifact: ...
    def create_artifact_version(self, project_id: UUID, parent_artifact_id: UUID, data: ArtifactCreate, created_by: str = "member-001", created_by_kind: str = "member") -> Artifact: ...
    def store_artifact_content(self, artifact_id: UUID, content: bytes, mime_type: str | None = None, expected_hash: str | None = None) -> Artifact: ...
    def get_artifact_content(self, artifact_id: UUID) -> bytes: ...
    def initiate_artifact_multipart(self, artifact_id: UUID, mime_type: str | None = None) -> dict[str, object]: ...
    def upload_artifact_part(self, artifact_id: UUID, upload_id: str, part_number: int, content: bytes) -> str: ...
    def complete_artifact_multipart(self, artifact_id: UUID, upload_id: str, expected_hash: str | None = None) -> Artifact: ...
    def abort_artifact_multipart(self, artifact_id: UUID, upload_id: str) -> None: ...
    def cleanup_stale_artifact_multipart_uploads(self, max_age_seconds: int = 86400) -> int: ...
    def archive_artifact(self, artifact_id: UUID) -> Artifact: ...
    def get_document_draft(self, project_id: UUID, artifact_id: UUID) -> DocumentDraft | None: ...
    def save_document_draft(self, project_id: UUID, artifact_id: UUID, content: str, *, base_revision: int, updated_by: str) -> DocumentDraft: ...
    def import_artifact(self, project_id: UUID, **kwargs: object) -> tuple[Artifact, bool]: ...
    def list_gates(self, project_id: UUID) -> list[Gate]: ...
    def create_evidence(self, project_id: UUID, data: EvidenceCreate) -> Evidence: ...
    def list_evidence(self, project_id: UUID) -> list[Evidence]: ...
    def register_git_repository(self, data: GitRepositoryCreate) -> GitRepository: ...
    def get_git_repository(self, project_id: UUID) -> GitRepository: ...
    def index_git_repository(self, project_id: UUID, commit_sha: str | None = None) -> list[GitFileIndex]: ...
    def list_git_index(self, project_id: UUID, commit_sha: str | None = None) -> list[GitFileIndex]: ...
    def list_agents(self) -> list[Agent]: ...
    def register_agent(self, data: AgentRegister) -> Agent: ...
    def heartbeat(self, agent_id: str) -> Agent: ...
    def unregister_agent(self, agent_id: str) -> None: ...
    def get_device(self, device_id: str) -> Device: ...
    def list_devices_for_member(self, member_id: str) -> list[Device]: ...
    def get_device_runtime_state(self, device_id: str) -> DeviceRuntimeState | None: ...
    def list_device_project_grants_for_device(self, device_id: str) -> list[DeviceProjectGrant]: ...
    def create_device_pairing(self, data: DevicePairingCreate, created_by: str) -> DevicePairing: ...
    def register_device(self, data: DeviceRegisterRequest) -> DeviceCredential: ...
    def resolve_device_token(self, device_token: str) -> Device: ...
    def rotate_device_token(self, device_id: str, rotated_by: str, reason: str = "rotated_by_member") -> DeviceCredential: ...
    def revoke_device(self, device_id: str, revoked_by: str, reason: str = "revoked_by_member") -> Device: ...
    def create_device_project_grant(self, project_id: UUID, data: DeviceProjectGrantCreate, granted_by: str) -> DeviceProjectCredential: ...
    def list_device_project_grants(self, project_id: UUID, member_id: str) -> list[DeviceProjectGrant]: ...
    def revoke_device_project_grant(self, grant_id: UUID, revoked_by: str) -> DeviceProjectGrant: ...
    def resolve_device_project_token(self, project_token: str, project_id: UUID, capability: str | None = None) -> DeviceProjectGrant: ...
    def open_agent_connection(self, device_id: str, session_id: str, connection_id: str, transport: str = "websocket") -> AgentConnection: ...
    def get_agent_connection(self, connection_id: str) -> AgentConnection: ...
    def record_gateway_receive(self, connection_id: str, sequence: int) -> tuple[str, int]: ...
    def next_gateway_send_sequence(self, connection_id: str) -> int: ...
    def record_agent_heartbeat(self, connection_id: str, heartbeat: Any) -> AgentConnection: ...
    def close_agent_connection(self, connection_id: str, status: str = "DISCONNECTED") -> AgentConnection: ...
    def get_gateway_command_result(
        self,
        connection_id: str,
        *,
        message_id: str | None = None,
        idempotency_key: str | None = None,
    ) -> GatewayCommandResult | None: ...
    def save_gateway_command_result(self, result: GatewayCommandResult) -> GatewayCommandResult: ...
    def create_review(self, project_id: UUID, data: ReviewCreate) -> Review: ...
    def list_risks(self, project_id: UUID) -> list[RiskRegistryEntry]: ...
    def update_risk(self, project_id: UUID, risk_id: UUID, data: RiskDecisionRequest, actor: str = "member-001") -> RiskRegistryEntry: ...
    def list_events(self, project_id: UUID, after: int = 0, limit: int = 100) -> list[Event]: ...
    def get_event(self, event_id: UUID) -> Event: ...
    def add_event(self, project_id: UUID, event_type: str, actor: str, payload: dict[str, Any], **kwargs: Any) -> Event: ...
    def list_event_outbox(self, project_id: UUID | None = None, *, status: str | None = None, limit: int = 100) -> list[EventOutbox]: ...
    def list_pending_event_outbox(self, limit: int = 100) -> list[EventOutbox]: ...
    def claim_event_outbox(self, limit: int = 100, lock_seconds: int = 60) -> list[EventOutbox]: ...
    def mark_event_outbox_delivered(self, outbox_id: UUID) -> EventOutbox: ...
    def mark_event_outbox_failed(self, outbox_id: UUID, error: str, retry_at: datetime | None = None) -> EventOutbox: ...
    def get_idempotent_response(self, key: str, operation: str, request_hash: str | None = None) -> Any | None: ...
    def save_idempotent_response(self, key: str, operation: str, response: Any, request_hash: str | None = None) -> None: ...
